%YAML:1.0
app:
  input_source: "mvs:0"           # mvs:0 使用 Hikrobot MVS SDK 的第 0 台相机
  onnx_model_path: "models/best_opset12.onnx"
  class_names_path: "config/classes.txt"
  calibration_file: "../camera"
  focal_length_mm: 8.0
  pixel_size_um: 4.0

  frame_width: 1280
  frame_height: 1024
  max_frames: -1
  queue_size: 6
  infer_interval: 2
  measure_interval: 2
  render_interval: 2

  conf_threshold: 0.35
  nms_threshold: 0.30

  caliper_length: -1.0
  caliper_half_width: 8.0
  gaussian_sigma: 1.0
  caliper_search_scale: 1.25
  use_obb_adaptive_caliper: 1
  measure_long_edge: 1

  show_window: 1
  enable_diag_logs: 0
  strict_calibration: 1
